apiVersion: v1
kind: Service
metadata:
    name: www-service
spec:
    selector:
        app: www
    ports:
        - protocol: TCP
          name: www
          port: 80
          targetPort: 80
    type: LoadBalancer
